---
- name: Ensure docker group exists
  become: yes
  group:
    name: docker
    state: present

- name: Ensure '{{ raspberry_user }}' user is added to docker group
  become: yes
  user:
    name: '{{ raspberry_user }}'
    groups: docker
    append: yes

- name: Ensure aufs-tools apt preferences is set to not instal
  become: yes
  copy:
    dest: /etc/apt/preferences.d/aufs-tools
    src: files/aufs-tools

- name: Ensure docker is installed
  include_role:
    name: geerlingguy.docker
  vars:
    ansible_become: yes
    # Override the defaults here to support raspbian
    docker_apt_arch: 'armhf'
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
  register: docker_install

- name: Ensure docker python library is installed
  become: yes
  package:
    name: python-docker
    state: present
    
- name: Ensure Docker api is started
  wait_for:
    timeout: 60

- name: Ensure pihole docker container is running
  become: yes
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart: no
    restart_policy: unless-stopped
    ports:
    - '53:53/udp' #dns
    - '53:53/tcp' #dns
    - '67:67/udp' #dhcp
    - '80:80/tcp' #web interface
    - '443:443/tcp' #web interface
    volumes:
    - ./etc-pihole/:/etc/pihole/
    - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    env:
      DNS1: '{{ dns_server1 }}'
      DNS2: '{{ dns_server2 }}'
      WEBPASSWORD: "{{ pihole_admin_password }}"